"""add width height to project_clips

Revision ID: 19d06744f170
Revises: adcecb0d0c48
Create Date: 2026-06-26 14:37:39.719237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d06744f170'
down_revision: Union[str, Sequence[str], None] = 'adcecb0d0c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_clips', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('project_clips', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_clips', 'height')
    op.drop_column('project_clips', 'width')
    # ### end Alembic commands ###
