"""baseline

Revision ID: 82d095a677db
Revises: 
Create Date: 2026-06-25 15:21:41.432696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82d095a677db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('clip_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', postgresql.ENUM('convert_clip', 'analyze_clip', 'render_final', 'full_pipeline', name='job_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'succeeded', 'failed', name='job_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('cloud_run_execution_name', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['project_clips.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('clip_id', sa.Uuid(), nullable=True),
    sa.Column('kind', postgresql.ENUM('original_clip', 'converted_clip', 'scene_candidates', 'final_clip', name='asset_kind'), nullable=False),
    sa.Column('storage_provider', postgresql.ENUM('gcs', 'r2', name='storage_provider'), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['project_clips.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_assets')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
