"""add on delete cascade

Revision ID: adcecb0d0c48
Revises: 82d095a677db
Create Date: 2026-06-25 19:13:17.010271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcecb0d0c48'
down_revision: Union[str, Sequence[str], None] = '82d095a677db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('processing_jobs_clip_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.drop_constraint(op.f('processing_jobs_project_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'project_clips', ['clip_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'processing_jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_assets_clip_id_fkey'), 'project_assets', type_='foreignkey')
    op.drop_constraint(op.f('project_assets_project_id_fkey'), 'project_assets', type_='foreignkey')
    op.create_foreign_key(None, 'project_assets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_assets', 'project_clips', ['clip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_clips_project_id_fkey'), 'project_clips', type_='foreignkey')
    op.create_foreign_key(None, 'project_clips', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_clips', type_='foreignkey')
    op.create_foreign_key(op.f('project_clips_project_id_fkey'), 'project_clips', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_assets', type_='foreignkey')
    op.drop_constraint(None, 'project_assets', type_='foreignkey')
    op.create_foreign_key(op.f('project_assets_project_id_fkey'), 'project_assets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_assets_clip_id_fkey'), 'project_assets', 'project_clips', ['clip_id'], ['id'])
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('processing_jobs_project_id_fkey'), 'processing_jobs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('processing_jobs_clip_id_fkey'), 'processing_jobs', 'project_clips', ['clip_id'], ['id'])
    # ### end Alembic commands ###
