/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Project Endpoint
         * @description project作成、status=draft、access_token返却。
         */
        post: operations["create_project_endpoint_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Prepare Endpoint
         * @description 全clipがuploadedならprepare worker起動、project.status=preparing。
         */
        post: operations["start_prepare_endpoint_projects__project_id__prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Render Endpoint
         * @description editConfigを保存しrender worker起動、project.status=rendering。
         */
        post: operations["start_render_endpoint_projects__project_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Status Endpoint
         * @description project.statusに応じて進捗・解析結果・エラー情報を返す。
         */
        get: operations["get_project_status_endpoint_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/clips/upload-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Upload Urls Endpoint
         * @description 動画のバリデーション、複数clip作成、GCSアップロード用signed URL発行、project.status=uploading。
         */
        post: operations["request_upload_urls_endpoint_projects__project_id__clips_upload_urls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clips/{clip_id}/upload-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Complete Upload Endpoint
         * @description project idを探してaccess_tokenを照合、clip単位でアップロード完了通知、GCS object存在確認、
         *     project_clips.status=uploaded。
         */
        put: operations["complete_upload_endpoint_clips__clip_id__upload_complete_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{share_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Share Page Endpoint
         * @description 認証不要で完成動画の共有閲覧情報を返す。
         */
        get: operations["get_share_page_endpoint_share__share_slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClipUploadRequestBody */
        ClipUploadRequestBody: {
            /** Originalfilename */
            originalFilename: string;
            /** Contenttype */
            contentType: string;
            /** Sizebytes */
            sizeBytes: number;
        };
        /** ClipUploadUrlResponse */
        ClipUploadUrlResponse: {
            /**
             * Clipid
             * Format: uuid
             */
            clipId: string;
            /** Clipindex */
            clipIndex: number;
            /** Uploadurl */
            uploadUrl: string;
        };
        /** ClipVideoResponse */
        ClipVideoResponse: {
            /** Url */
            url: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
        };
        /** CompleteUploadResponse */
        CompleteUploadResponse: {
            /**
             * Clipid
             * Format: uuid
             */
            clipId: string;
            /** Status */
            status: string;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /**
             * Deviceid
             * Format: uuid
             */
            deviceId: string;
        };
        /** CreateProjectResponse */
        CreateProjectResponse: {
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Status */
            status: string;
            /** Accesstoken */
            accessToken: string;
        };
        /** EditConfigRequest */
        EditConfigRequest: {
            /** Version */
            version: number;
            /**
             * Transition
             * @enum {string}
             */
            transition: "none" | "fade";
            /** Timeline */
            timeline: components["schemas"]["TimelineCutRequest"][];
        };
        /** GetProjectStatusResponse */
        GetProjectStatusResponse: {
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Status */
            status: string;
            /** Clipstotal */
            clipsTotal?: number | null;
            /** Clipsready */
            clipsReady?: number | null;
            /** Clips */
            clips?: components["schemas"]["ReadyClipResponse"][] | null;
            /** Errorphase */
            errorPhase?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /** Shareurl */
            shareUrl?: string | null;
            /** Finalvideourl */
            finalVideoUrl?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ReadyClipResponse */
        ReadyClipResponse: {
            /**
             * Clipid
             * Format: uuid
             */
            clipId: string;
            /** Clipindex */
            clipIndex: number;
            /** Durationms */
            durationMs: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            video: components["schemas"]["ClipVideoResponse"];
            /** Scenes */
            scenes: components["schemas"]["SceneResponse"][];
        };
        /** RequestUploadUrlsRequest */
        RequestUploadUrlsRequest: {
            /** Clips */
            clips: components["schemas"]["ClipUploadRequestBody"][];
        };
        /** SceneResponse */
        SceneResponse: {
            /**
             * Sceneid
             * Format: uuid
             */
            sceneId: string;
            /** Sceneindex */
            sceneIndex: number;
            /** Startms */
            startMs: number;
            /** Endms */
            endMs: number;
            /** Labels */
            labels: string[];
        };
        /** SharePageResponse */
        SharePageResponse: {
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Videourl */
            videoUrl: string;
        };
        /** StartPrepareResponse */
        StartPrepareResponse: {
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Status */
            status: string;
        };
        /** StartRenderRequest */
        StartRenderRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            editConfig: components["schemas"]["EditConfigRequest"];
        };
        /** StartRenderResponse */
        StartRenderResponse: {
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Status */
            status: string;
        };
        /** TimelineCutRequest */
        TimelineCutRequest: {
            /** Cutid */
            cutId: string;
            /** Order */
            order: number;
            /**
             * Clipid
             * Format: uuid
             */
            clipId: string;
            /** Startms */
            startMs: number;
            /** Endms */
            endMs: number;
            transform: components["schemas"]["TransformRequest"];
        };
        /** TransformRequest */
        TransformRequest: {
            /** Zoom */
            zoom: number;
            /** Offsetx */
            offsetX: number;
            /** Offsety */
            offsetY: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_project_endpoint_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_prepare_endpoint_projects__project_id__prepare_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartPrepareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_render_endpoint_projects__project_id__render_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_status_endpoint_projects__project_id__get: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProjectStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_upload_urls_endpoint_projects__project_id__clips_upload_urls_post: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestUploadUrlsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipUploadUrlResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_endpoint_clips__clip_id__upload_complete_put: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path: {
                clip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_page_endpoint_share__share_slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharePageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
